# Created by: Ruth De Paula

import os
import subprocess

g=["GGGGTGGGGGGAGGGGGGAGGG", "GGGGAGGGGGGAGGGGGGAGGG", "GGGGCGGGGGGCGGGGGGCGGG", "GGGGTGGGGGGTGGGGGGTGGG", "GGGGAGGGGGGAGGGGGGCGGG", "GGGGAGGGGGGAGGGGGGTGGG", "GGGGCGGGGGGCGGGGGGAGGG", "GGGGCGGGGGGCGGGGGGTGGG", "GGGGTGGGGGGTGGGGGGAGGG", "GGGGTGGGGGGTGGGGGGCGGG", "GGGGAGGGGGGCGGGGGGCGGG", "GGGGAGGGGGGTGGGGGGTGGG", "GGGGCGGGGGGAGGGGGGAGGG", "GGGGCGGGGGGTGGGGGGTGGG", "GGGGTGGGGGGCGGGGGGCGGG", "GGGGAGGGGGGCGGGGGGTGGG", "GGGGAGGGGGGTGGGGGGCGGG", "GGGGCGGGGGGAGGGGGGTGGG", "GGGGCGGGGGGTGGGGGGAGGG", "GGGGTGGGGGGAGGGGGGCGGG", "GGGGTGGGGGGCGGGGGGAGGG", "GGGGAGGGGGGCGGGGGGAGGG", "GGGGAGGGGGGTGGGGGGAGGG", "GGGGCGGGGGGAGGGGGGCGGG", "GGGGCGGGGGGTGGGGGGCGGG", "GGGGTGGGGGGAGGGGGGTGGG", "GGGGTGGGGGGCGGGGGGTGGG"]
fum=["CCCTCCCCCCTCCCCCCACCCC", "CCCTCCCCCCTCCCCCCTCCCC", "CCCGCCCCCCGCCCCCCGCCCC", "CCCACCCCCCACCCCCCACCCC", "CCCGCCCCCCTCCCCCCTCCCC", "CCCACCCCCCTCCCCCCTCCCC", "CCCTCCCCCCGCCCCCCGCCCC", "CCCACCCCCCGCCCCCCGCCCC", "CCCTCCCCCCACCCCCCACCCC", "CCCGCCCCCCACCCCCCACCCC", "CCCGCCCCCCGCCCCCCTCCCC", "CCCACCCCCCACCCCCCTCCCC", "CCCTCCCCCCTCCCCCCGCCCC", "CCCACCCCCCACCCCCCGCCCC", "CCCGCCCCCCGCCCCCCACCCC", "CCCACCCCCCGCCCCCCTCCCC", "CCCGCCCCCCACCCCCCTCCCC", "CCCACCCCCCTCCCCCCGCCCC", "CCCTCCCCCCACCCCCCGCCCC", "CCCGCCCCCCTCCCCCCACCCC", "CCCTCCCCCCGCCCCCCACCCC", "CCCTCCCCCCGCCCCCCTCCCC", "CCCTCCCCCCACCCCCCTCCCC", "CCCGCCCCCCTCCCCCCGCCCC", "CCCGCCCCCCACCCCCCGCCCC", "CCCACCCCCCTCCCCCCACCCC", "CCCACCCCCCGCCCCCCACCCC"]

for i in range(len(g)):
        cmd="cat plus_strand_"+g[i]+" minus_strand_"+fum[i]+" > both_strand_"+g[i]+""
        print(cmd)
        process = subprocess.Popen(cmd, shell=True,stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        # wait for the process to terminate
        out, err = process.communicate()
        errcode = process.returncode
        print(out)
        print(err)
